services:
  useless_guessing:
    image: cybersecnatlab/challenge-jail@sha256:2d1e046fa7bb27a6b7d1dba44379b722c0498b40bf9db1a84c47be1ecc09752a
    restart: unless-stopped
    init: true
    privileged: true
    volumes:
      - './build/useless_guessing:/home/user/chall:ro'
    ports:
      - '1337:1337'
    environment:
      - 'FLAG=flag{fake_flag}'
      - 'LOG_SDTERR=true'
      - 'TIMEOUT=120'
